name: "🐛 Bug Report"
description: Report something that isn't working as expected.
title: "[Bug] <Short description of the issue>"
labels: ["bug"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Preliminary Checks
      description: Please confirm the following before submitting your bug report.
      options:
        - label: I have searched [existing issues](../issues) and [pull requests](../pulls) for duplicates.
          required: true
        - label: I have read the [contributing guidelines](../blob/main/CONTRIBUTING.md) (if applicable).
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: |
        When I try to [...], I get this unexpected behavior [...]

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?

  - type: input
    id: version
    attributes:
      label: Affected Version/Commit
      description: Version number, branch name, or commit hash where the bug occurs.

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did the issue occur?
      options:
        - Local development
        - Production
        - CI/CD
        - Other

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs, Screenshots, or Stack Traces
      description: Paste any error messages or screenshots that can help diagnose the issue.
      render: shell

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Anything else we should know?
