name: Continous Delivery
on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  SERVICE: credo-controller

jobs:
  build-and-push:
    name: Push Docker image to GitHub
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Git Tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Patch Dockerfile with network timeout
        run: |
          cp Dockerfile Dockerfile.ci
          sed -i 's|yarn install --frozen-lockfile|yarn install --frozen-lockfile --network-timeout 600000|' Dockerfile.ci

      - name: Build and Push Docker Image ${{ env.SERVICE }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.SERVICE }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.SERVICE }}:latest
          

